# Generated by Django 2.1.7 on 2020-01-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='abc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursetitle', models.CharField(max_length=45, null=True)),
                ('coursetype', models.CharField(max_length=45, null=True)),
                ('coursefull', models.FileField(upload_to='')),
                ('coursedesc', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workoutname', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='imagee/pdf')),
                ('email', models.EmailField(max_length=254)),
                ('workoutdesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=45)),
                ('contact', models.IntegerField(max_length=14)),
                ('course', models.ManyToManyField(null=True, to='gymapp.abc')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_fname', models.CharField(max_length=45)),
                ('pay_lname', models.CharField(max_length=45)),
                ('pay_address', models.CharField(max_length=60)),
                ('pay_city', models.CharField(max_length=30)),
                ('pay_state', models.CharField(max_length=30)),
                ('pay_account_number', models.IntegerField(max_length=20)),
                ('pay_date', models.DateTimeField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.abc')),
                ('members', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.Members')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=45, null=True)),
                ('lname', models.CharField(max_length=45, null=True)),
                ('username', models.CharField(max_length=45, null=True)),
                ('categories', models.CharField(max_length=45, null=True)),
                ('email', models.EmailField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.Members')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.abc')),
            ],
        ),
        migrations.AddField(
            model_name='abc',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gymapp.Trainer'),
        ),
    ]
